/// Today's cited actions, as legacy's one collapsible block.
///
/// **Ported from** `healthee-legacy/app/lib/ui/today_screen.dart:896` —
/// `_ActionsSection` and `_ActionRow`. Geometry unchanged:
///
/// ```text
///   ┌──────────────────────────────────────────────┐
///   │ 💡  Suggested actions                      ›  │  15/13 padding, badge 38
///   │     3 ways to improve today                   │
///   └──────────────────────────────────────────────┘
///        ↓ tap — AnimatedSize, 280 ms, legacy's ease
///   ┌──────────────────────────────────────────────┐
///   │ ●  Sleep earlier tonight                   ›  │  8 px dot, 14 padding
///   │    ↓ tap — AnimatedSize, 220 ms               │
///   │    Debt is 120 min                            │
///   │    ┌────────────────────────────────────────┐ │
///   │    │ ⊙  Lower debt                          │ │  the sunken effect block
///   │    └────────────────────────────────────────┘ │
///   └──────────────────────────────────────────────┘
/// ```
///
/// Both levels are **collapsed by default**, which is legacy's decision and a
/// good one: the actions are the only thing on Today written by a model, and a
/// screen that opens with them puts generated prose above measurements.
///
/// ## Every string here is model prose, and none of it is printed raw
///
/// `action`, `rationale` and `expected_effect` are three of the four LLM fields
/// on `/api/today`, and they arrive with inline `[note_id]` markers. Legacy
/// printed the markers. All three go through [GroundedProse] here, which is the
/// only thing in the app that knows what a bracket means — there is no parameter
/// that turns the sources off, and a bracket that resolves to nothing is left in
/// the sentence and announced rather than deleted.
///
/// The sources are in the ⓘ on each row, not under the prose. One recommendation
/// is one claim written three ways — action, rationale, expected effect — so the
/// row's ⓘ carries all three fields' markers, the rec's structured
/// `research_note_ids` and its **proved** grade, as one set.
///
/// The block's own head has an ⓘ too, for `/api/today`'s top-level `action`:
/// that string is generated by a different job and cites its own notes, so
/// folding it into a row's sheet would say a rec was backed by a source it never
/// named. Both dots vanish entirely when the prose behind them cites nothing.
library;

import 'package:flutter/material.dart';
import 'package:healthee/core/theme/dimensions.dart';
import 'package:healthee/core/theme/instrument_hues.dart';
import 'package:healthee/core/theme/instrument_type.dart';
import 'package:healthee/core/theme/motion.dart';
import 'package:healthee/core/theme/tokens.dart';
import 'package:healthee/data/honesty/citations.dart';
import 'package:healthee/data/models/recommendation.dart';
import 'package:healthee/shared/format/date_labels.dart';
import 'package:healthee/shared/instrument/h_icon_badge.dart';
import 'package:healthee/shared/instrument/h_tap.dart';
import 'package:healthee/shared/instrument_module.dart';
import 'package:healthee/shared/metric_info/metric_detail.dart';
import 'package:healthee/shared/metric_info/metric_info_sheet.dart';
import 'package:healthee/shared/states/grounded_text.dart';
import 'package:solar_icons/solar_icons.dart';

/// Legacy's own heading for the block, and what its ⓘ falls back to naming.
const String kSuggestedActions = 'Suggested actions';

/// What the block says when the actions were written for a different day.
///
/// Public so a test can pin the wording rather than re-typing it.
String actionsFromDay(String isoDay) =>
    'Written for ${shortDate(isoDay)} — nothing was written for this day.';

/// The collapsible "Suggested actions" block.
class ActionsSection extends StatefulWidget {
  /// [recommendations] is the day's set, highest rank first.
  const ActionsSection({
    required this.recommendations,
    this.action,
    this.viewedDay,
    super.key,
  });

  /// Today's cited actions.
  final List<Recommendation> recommendations;

  /// The day this screen is answering for, `YYYY-MM-DD` — `as_of.day`.
  ///
  /// `read/today.py::_recommendations_for` serves the newest recommendation set
  /// dated **at or before** the day being viewed, reaching back two days. So
  /// this block is not always showing that day's actions, and without the day
  /// it is showing them under a heading that says otherwise. Comparing the
  /// server's `as_of.day` against each row's own `date` is the only way the
  /// client can tell; a device clock cannot, which is the argument
  /// `data/models/as_of.dart` already makes about `isToday`.
  ///
  /// Null means the payload carried no `as_of` — an older server — and then the
  /// block claims nothing about which day these are for, rather than guessing.
  final String? viewedDay;

  /// The recommendations' own day when it is NOT [viewedDay], else null.
  ///
  /// Static and pure so the decision is testable without a widget tree, and so
  /// there is one definition of "these are from another day". All rows in a set
  /// share a date (the server keeps only the newest date found), so the first
  /// row speaks for the set.
  static String? otherDay(List<Recommendation> items, String? viewedDay) {
    final String? day = items.isEmpty ? null : items.first.date;
    if (day == null || viewedDay == null || day == viewedDay) {
      return null;
    }
    return day;
  }

  /// `/api/today`'s own top-level `action` — the model's one-line daily
  /// suggestion, **which no legacy file renders**. Legacy reads only
  /// `recommendations[].action` (`today_screen.dart:967`), so this string has
  /// been generated nightly and shown to nobody.
  ///
  /// It goes in the subtitle slot of the block it belongs to, replacing the
  /// generic "N ways to improve today" when the server has warmed one. Null
  /// renders that generic line and nothing else — `docs/APP_DESIGN.md` §3.1:
  /// null means show nothing, never a spinner.
  final String? action;

  @override
  State<ActionsSection> createState() => _ActionsSectionState();
}

class _ActionsSectionState extends State<ActionsSection> {
  bool _open = false;

  /// What `/api/today`'s own top-level `action` cites, if anything.
  MetricDetail _dailyDetail() {
    final daily = widget.action;
    return daily == null
        ? MetricDetail.none
        : MetricDetail.grounded(groundingOf(daily));
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final items = widget.recommendations;
    // The daily `action` and the recommendation set are written by the same
    // nightly job and either can arrive without the other, so the block draws
    // for either. With neither it draws nothing at all.
    if (items.isEmpty && widget.action == null) {
      return const SizedBox.shrink();
    }
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        HTap(
          onTap: items.isEmpty ? null : () => setState(() => _open = !_open),
          semanticLabel: items.isEmpty
              ? null
              : (_open ? 'Hide suggested actions' : 'Show suggested actions'),
          child: InstrumentModule(
            label: '',
            tag: null,
            minHeight: 0,
            padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 13),
            children: [
              Row(
                children: [
                  HIconBadge(
                    SolarIconsBold.lightbulb,
                    color: colors.accent,
                    size: 38,
                    radius: 12,
                  ),
                  const SizedBox(width: 13),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          kSuggestedActions,
                          style: HType.serif(colors.ink, size: 17),
                        ),
                        const SizedBox(height: 2),
                        if (widget.action case final String daily)
                          GroundedProse(
                            text: daily,
                            style: HType.sans(colors.ink3, size: 12),
                            maxLines: 2,
                          )
                        else
                          Text(
                            '${items.length} '
                            '${items.length == 1 ? 'way' : 'ways'} to improve today',
                            style: HType.sans(colors.ink3, size: 12),
                          ),
                        // The rows' own day, said in words, whenever it is not
                        // the day on screen. Drawn under whichever subtitle ran
                        // above, because it qualifies the LIST rather than the
                        // daily line — `/api/today.action` is generated for the
                        // day it is served on and never reaches back.
                        if (ActionsSection.otherDay(items, widget.viewedDay)
                            case final String day) ...[
                          const SizedBox(height: 2),
                          Text(
                            actionsFromDay(day),
                            style: HType.sans(colors.ink3, size: 11),
                          ),
                        ],
                      ],
                    ),
                  ),
                  if (_dailyDetail() case final MetricDetail detail
                      when detail.isNotEmpty)
                    MetricInfoDot(
                      // The daily line is not about one metric, so there is no
                      // explainer key for it. Its own citations are the sheet.
                      null,
                      detail: detail,
                      fallbackTitle: kSuggestedActions,
                    ),
                  // No arrow with nothing to expand into: a control that
                  // opens an empty list is a dead control.
                  if (items.isNotEmpty)
                    AnimatedRotation(
                      turns: _open ? 0.25 : 0,
                      duration: HMotion.fast,
                      child: Icon(
                        SolarIconsOutline.altArrowRight,
                        size: 18,
                        color: colors.ink3,
                      ),
                    ),
                ],
              ),
            ],
          ),
        ),
        AnimatedSize(
          duration: const Duration(milliseconds: 280),
          curve: HMotion.curve,
          alignment: Alignment.topCenter,
          child: _open
              ? Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    for (final rec in items) ...[
                      const SizedBox(height: 8),
                      ActionRow(recommendation: rec),
                    ],
                  ],
                )
              : const SizedBox(width: double.infinity),
        ),
      ],
    );
  }
}

/// One action: its headline, and the reasoning behind it on tap.
class ActionRow extends StatefulWidget {
  /// [recommendation] is one cited action.
  const ActionRow({required this.recommendation, super.key});

  /// What to do, why, and what it should change.
  final Recommendation recommendation;

  @override
  State<ActionRow> createState() => _ActionRowState();
}

class _ActionRowState extends State<ActionRow> {
  bool _open = false;

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final rec = widget.recommendation;
    final tint = categoryColor(context, rec.category);
    return HTap(
      onTap: () => setState(() => _open = !_open),
      semanticLabel: _open ? 'Hide why' : 'Why this, today',
      child: InstrumentModule(
        label: '',
        tag: null,
        minHeight: 0,
        children: [
          Row(
            children: [
              Container(
                width: 8,
                height: 8,
                decoration: BoxDecoration(color: tint, shape: BoxShape.circle),
              ),
              const SizedBox(width: 11),
              Expanded(
                child: GroundedProse(
                  text: rec.action,
                  style: HType.sans(
                    colors.ink,
                    size: 14,
                    weight: FontWeight.w600,
                  ),
                  maxLines: _open ? null : 1,
                ),
              ),
              const SizedBox(width: 8),
              if (MetricDetail.grounded(rec.grounding, grade: rec.gradeLabel)
                  case final MetricDetail detail when detail.isNotEmpty)
                MetricInfoDot(
                  null,
                  detail: detail,
                  fallbackTitle: kSuggestedActions,
                ),
              AnimatedRotation(
                turns: _open ? 0.25 : 0,
                duration: HMotion.fast,
                child: Icon(
                  SolarIconsOutline.altArrowRight,
                  size: 16,
                  color: colors.ink3,
                ),
              ),
            ],
          ),
          AnimatedSize(
            duration: const Duration(milliseconds: 220),
            curve: HMotion.curve,
            alignment: Alignment.topCenter,
            child: !_open
                ? const SizedBox(width: double.infinity)
                : _Expanded(recommendation: rec, tint: tint),
          ),
        ],
      ),
    );
  }
}

/// The rationale, the expected effect, and the rec's own sources.
class _Expanded extends StatelessWidget {
  const _Expanded({required this.recommendation, required this.tint});

  final Recommendation recommendation;
  final Color tint;

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final rec = recommendation;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (rec.rationale case final String why) ...[
          const SizedBox(height: 10),
          GroundedProse(
            text: why,
            style: HType.sans(colors.ink2, size: 13, height: 1.5),
          ),
        ],
        if (rec.expectedEffect case final String effect) ...[
          const SizedBox(height: 10),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 11, vertical: 8),
            decoration: BoxDecoration(
              color: colors.surface2,
              borderRadius: BorderRadius.circular(Radii.badge),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Icon(SolarIconsOutline.target, size: 13, color: tint),
                const SizedBox(width: 7),
                Expanded(
                  child: GroundedProse(
                    text: effect,
                    style: HType.sans(colors.ink3, size: 11.5, height: 1.4),
                  ),
                ),
              ],
            ),
          ),
        ],
      ],
    );
  }
}

/// The dot colour for a recommendation's category. Legacy's `catColor` (899).
///
/// The `_` fallback is legacy's own green, so a category the server grows later
/// is drawn in the accent rather than in nothing.
Color categoryColor(BuildContext context, String? category) {
  final colors = context.colors;
  final hues = context.hues;
  return switch (category) {
    'sleep' => hues.sleep,
    'activity' => colors.accent,
    'fitness' => hues.fitness,
    'recovery' => hues.heart,
    'intake' => hues.movement,
    _ => colors.accent,
  };
}
