#!/usr/bin/env python3
"""Generate the knowledge manifest from both corpus collections.

Parses the YAML frontmatter of every doc in `notes/` and `sports-science/` (the
two collections differ in their optional fields, not in their grade), normalizes
them to one record shape, validates the whole corpus, and writes two committed,
diff-stable artifacts:

  * manifest.json           — full records, for server-side retrieval.
  * research_summaries.json  — compact records, for the mobile asset.

Both are GENERATED — never hand-edit them; run `make knowledge` to regenerate.
Validation is loud: a duplicate id, a bad id format, an unknown grade, a
reintroduced `evidence_grade`, or a missing required field aborts with a
non-zero exit and a clear message.

**One grade per note.** `grade` is the single source of truth for both
collections. The numeric `evidence_grade` mirror was removed in #83 — it could
disagree with `grade`, the winner depended on the note's directory, and it could
not express Contested or Myth at all. See :func:`_grade`.

Run:
    cd apps/server && uv run python ../../packages/knowledge/tools/gen_manifest.py
    # add --check to fail (non-zero) if the committed files are stale.

PyYAML is the only third-party dependency (declared in apps/server's dev group).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

KNOWLEDGE_ROOT = Path(__file__).resolve().parent.parent
NOTES_DIR = KNOWLEDGE_ROOT / "notes"
SS_DIR = KNOWLEDGE_ROOT / "sports-science"
MANIFEST_PATH = KNOWLEDGE_ROOT / "manifest.json"
SUMMARIES_PATH = KNOWLEDGE_ROOT / "research_summaries.json"

# Non-note markdown that must never be treated as evidence.
NOTES_SKIP = {"README.md", "conventions.md"}
SS_SKIP = {"README.md", "METHODOLOGY.md", "TEMPLATE.md", "COACHING-RULES.md"}

# The ONE grade vocabulary (Engineering Standards §4). `grade` is the single source
# of truth for every note in both collections — see `_grade` below for why the old
# numeric `evidence_grade` mirror was removed rather than merely reconciled.
UNIFIED_GRADES = frozenset({"Established", "Probable", "Emerging", "Contested", "Myth", "Refuted"})

# The retired numeric mirror. Kept ONLY as a rejection list: a note that reintroduces
# it fails generation loudly instead of quietly re-opening the split.
RETIRED_GRADE_FIELD = "evidence_grade"

ID_RE = re.compile(r"[a-z0-9_]+")
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)$", re.S)

GENERATED_NOTICE = (
    "GENERATED by packages/knowledge/tools/gen_manifest.py — do not hand-edit. "
    "Run `make knowledge` to regenerate."
)


class CorpusError(Exception):
    """One or more validation failures over the corpus."""


def _parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Split a doc into (frontmatter dict, body). Raises on malformed YAML."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise ValueError("no YAML frontmatter block")
    try:
        data = yaml.safe_load(match.group(1))
    except yaml.YAMLError as exc:
        raise ValueError(f"malformed YAML frontmatter: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("frontmatter is not a mapping")
    return data, match.group(2).strip()


def _as_list(value: Any) -> list[str]:
    return [str(v) for v in value] if isinstance(value, list) else []


def _authored(fm: dict[str, Any], field: str, *fallbacks: Any) -> str:
    """The author's own value for ``field``, else the first non-empty fallback.

    Both record builders read the SAME authored fields (``name``, ``summary``,
    ``aliases``); the fallbacks exist only for legacy notes written before those
    fields were part of the schema. An authored value always wins — the manifest
    is what retrieval ranks against and what the model is shown for the notes it
    did not pull in full, so a derived stand-in silently degrades grounding.
    """
    for candidate in (fm.get(field), *fallbacks):
        text = str(candidate).strip() if candidate is not None else ""
        if text:
            return text
    return ""


def _authored_aliases(fm: dict[str, Any]) -> list[str]:
    """Authored ``aliases``; legacy notes predating the field fall back to ``tags``.

    Aliases are written to make a note *findable* ("nightcap", "alcohol before
    bed"); tags classify it. They are not interchangeable, so tags are a last
    resort, never a replacement.
    """
    return _as_list(fm.get("aliases")) or _as_list(fm.get("tags"))


def _first_body_line(body: str) -> str:
    """First non-empty prose line, heading/list markers stripped."""
    for raw in body.splitlines():
        line = raw.strip().lstrip("#>-* ").strip()
        if line:
            return line
    return ""


def _rel(path: Path) -> str:
    return path.relative_to(KNOWLEDGE_ROOT).as_posix()


def _grade(fm: dict[str, Any], where: str, errors: list[str]) -> str:
    """The note's ONE grade, validated. Shared by both collections.

    ## Why there is only one grade field (#83, 2026-08-01)

    Notes used to carry TWO grades: an authored ``grade`` string and a numeric
    ``evidence_grade`` mirror. They could disagree, and which one won depended on
    the note's DIRECTORY — ``notes/`` was built from ``evidence_grade`` and its
    authored ``grade`` was ignored; ``sports-science/`` did the exact reverse. So a
    note could ship under a grade nobody wrote, and the worst case was not
    hypothetical arithmetic: ``grade: Myth`` with ``evidence_grade: 3`` published as
    **Established**, which is the manifest telling every downstream consumer to state
    a debunked claim plainly. ``insights/validator.py`` reads this string to decide
    whether a sentence needs hedging, ``_grade_floor`` reports it as the answer's
    evidence floor, and ``MIN_ACTIONABLE_RANK`` lets it drive a recommendation.

    The numeric field was also structurally incapable of the job: it spans 3/2/1
    only, so ``Contested`` and ``Myth`` had no numeric at all —
    ``running_form_metrics`` was authored ``Contested`` and forced to write
    ``evidence_grade: 1``, whose own published mapping says *Emerging*.

    So it is not reconciled, it is REMOVED: one field, one vocabulary, both
    collections, and the numeric rank derived from the string once in
    ``insights/manifest.py::GRADE_RANK`` (which can express Contested → 1, Myth → 0).
    Reintroducing the field is a generation error, not a warning.
    """
    if RETIRED_GRADE_FIELD in fm:
        errors.append(
            f"{where}: `{RETIRED_GRADE_FIELD}` was removed (#83) — it could disagree with "
            "`grade` and cannot express Contested/Myth. Delete it; `grade` is the only grade."
        )
    grade = fm.get("grade")
    if grade is None:
        errors.append(f"{where}: missing required field `grade`")
        return ""
    if grade not in UNIFIED_GRADES:
        errors.append(f"{where}: unknown grade {grade!r} (allowed: {sorted(UNIFIED_GRADES)})")
        return ""
    return str(grade)


def _legacy_record(path: Path, errors: list[str]) -> dict[str, Any] | None:
    """Build a record for a legacy note, or None to skip a non-evidence doc."""
    fm, body = _parse_frontmatter(path.read_text())
    if "id" not in fm:
        return None  # engineering/protocol reference — not citable evidence
    where = _rel(path)
    note_id = str(fm.get("id") or "")
    if not note_id:
        errors.append(f"{where}: legacy note missing required field `id`")
    name = _authored(fm, "name", fm.get("topic"), fm.get("title"), note_id)
    summary = _authored(
        fm, "summary", fm.get("topic"), fm.get("title"), _first_body_line(body), name
    )
    return {
        "id": note_id,
        "name": name,
        "aliases": _authored_aliases(fm),
        "category": _authored(fm, "category", path.parent.name),
        "grade": _grade(fm, where, errors),
        "applies_to_metrics": _as_list(fm.get("applies_to_metrics")),
        "applies_to_interventions": _as_list(fm.get("applies_to_interventions")),
        "summary": summary,
        "population": fm.get("population"),
        "path": where,
        "collection": "legacy",
        "last_reviewed": fm.get("last_reviewed") and str(fm["last_reviewed"]),
    }


SS_REQUIRED = (
    "id",
    "name",
    "category",
    "summary",
    "aliases",
    "applies_to_metrics",
    "applies_to_interventions",
)


def _ss_record(path: Path, errors: list[str]) -> dict[str, Any]:
    """Build a record for a unified sports-science doc."""
    fm, _ = _parse_frontmatter(path.read_text())
    where = _rel(path)
    missing = [k for k in SS_REQUIRED if k not in fm]
    if missing:
        errors.append(f"{where}: missing required field(s): {', '.join(missing)}")
    return {
        "id": str(fm.get("id") or ""),
        "name": _authored(fm, "name"),
        "aliases": _authored_aliases(fm),
        "category": _authored(fm, "category", path.parent.name),
        "grade": _grade(fm, where, errors) if "grade" in fm else "",
        "applies_to_metrics": _as_list(fm.get("applies_to_metrics")),
        "applies_to_interventions": _as_list(fm.get("applies_to_interventions")),
        "summary": _authored(fm, "summary"),
        "population": fm.get("population"),
        "path": where,
        "collection": "sports_science",
        "last_reviewed": fm.get("last_reviewed") and str(fm["last_reviewed"]),
    }


def _iter_docs(root: Path, skip: set[str]) -> list[Path]:
    return sorted(p for p in root.rglob("*.md") if p.name not in skip)


def _collect(errors: list[str], skipped: list[str]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in _iter_docs(NOTES_DIR, NOTES_SKIP):
        try:
            record = _legacy_record(path, errors)
        except ValueError as exc:
            errors.append(f"{_rel(path)}: {exc}")
            continue
        if record is None:
            skipped.append(_rel(path))
        else:
            records.append(record)
    for path in _iter_docs(SS_DIR, SS_SKIP):
        try:
            records.append(_ss_record(path, errors))
        except ValueError as exc:
            errors.append(f"{_rel(path)}: {exc}")
    return records


def _validate(records: list[dict[str, Any]], errors: list[str]) -> None:
    seen: dict[str, str] = {}
    for record in records:
        rid = record["id"]
        if rid and not ID_RE.fullmatch(rid):
            errors.append(f"{record['path']}: id {rid!r} is not snake_case ([a-z0-9_]+)")
        if rid in seen:
            errors.append(f"duplicate id {rid!r}: {seen[rid]} and {record['path']}")
        elif rid:
            seen[rid] = record["path"]


def _prune(record: dict[str, Any]) -> dict[str, Any]:
    """Drop keys whose value is None so absent fields stay out of the JSON."""
    return {k: v for k, v in record.items() if v is not None}


def build_records() -> tuple[list[dict[str, Any]], list[str]]:
    """Parse + validate the whole corpus.

    Returns (records, skipped_paths). Raises CorpusError on any validation
    failure. Skipped paths are non-citable engineering/protocol notes (no `id`)
    — surfaced, never silently dropped.
    """
    errors: list[str] = []
    skipped: list[str] = []
    records = _collect(errors, skipped)
    _validate(records, errors)
    if errors:
        raise CorpusError("\n".join(f"  - {e}" for e in errors))
    records.sort(key=lambda r: r["id"])
    return [_prune(r) for r in records], sorted(skipped)


def _dumps(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def render_manifest(records: list[dict[str, Any]]) -> str:
    return _dumps({"_generated": GENERATED_NOTICE, "records": records})


def render_summaries(records: list[dict[str, Any]]) -> str:
    summaries = [
        {
            "id": r["id"],
            "name": r["name"],
            "grade": r["grade"],
            "summary": r["summary"],
            "applies_to_metrics": r["applies_to_metrics"],
        }
        for r in records
    ]
    return _dumps({"_generated": GENERATED_NOTICE, "summaries": summaries})


def _report(records: list[dict[str, Any]], skipped: list[str]) -> None:
    by_collection: dict[str, int] = {}
    for r in records:
        by_collection[r["collection"]] = by_collection.get(r["collection"], 0) + 1
    counts = ", ".join(f"{k}={v}" for k, v in sorted(by_collection.items()))
    print(f"knowledge manifest: {len(records)} records ({counts})")
    if skipped:
        print(f"  skipped {len(skipped)} non-citable engineering note(s): {', '.join(skipped)}")


def main(argv: list[str]) -> int:
    check = "--check" in argv
    try:
        records, skipped = build_records()
    except CorpusError as exc:
        print("knowledge manifest: VALIDATION FAILED", file=sys.stderr)
        print(str(exc), file=sys.stderr)
        return 1
    outputs = {MANIFEST_PATH: render_manifest(records), SUMMARIES_PATH: render_summaries(records)}
    if check:
        stale = [p.name for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        if stale:
            print(
                f"knowledge manifest: STALE — regenerate with `make knowledge`: {stale}",
                file=sys.stderr,
            )
            return 1
        _report(records, skipped)
        print("knowledge manifest: up to date")
        return 0
    for path, text in outputs.items():
        path.write_text(text)
    _report(records, skipped)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
