/* Motion acceptance: measurements stay stable; access and navigation can stop motion. */
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const baseURL = process.env.PREVIEW_URL || 'http://127.0.0.1:8765';
async function main() {
  const browser = await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:414,height:896}});
  page.on('pageerror',error=>console.error('Browser error:',error.message));
  try {
    await page.goto(baseURL);
    await page.evaluate(() => document.fonts.ready);
    await page.waitForFunction(() => document.querySelector('.bio-hero')?.dataset.ambient === 'running');
    assert.equal(await page.locator('#main h1').textContent(), 'Today');
    assert.equal(await page.locator('.age-value').textContent(), '34.3years');
    const halo = page.locator('.bio-halo');
    const atmosphere = page.locator('.bio-atmosphere');
    const ambientFirst = await atmosphere.evaluate(el => el.toDataURL());
    const first = await halo.evaluate(el => el.toDataURL());
    await page.waitForTimeout(250);
    assert.notEqual(await halo.evaluate(el => el.toDataURL()), first);
    assert.notEqual(await atmosphere.evaluate(el => el.toDataURL()), ambientFirst);
    await page.getByRole('button',{name:'Pause animations',exact:true}).click();
    assert.equal(await page.locator('html').getAttribute('data-motion'), 'off');
    const userPaused = await halo.evaluate(el => el.toDataURL());
    const ambientPaused = await atmosphere.evaluate(el => el.toDataURL());
    await page.waitForTimeout(150);
    assert.equal(await halo.evaluate(el => el.toDataURL()),userPaused);
    assert.equal(await atmosphere.evaluate(el => el.toDataURL()),ambientPaused);
    assert.equal(await page.locator('#main').evaluate(el => el.getAnimations({subtree:true}).length), 0);
    await page.getByRole('button',{name:'Resume animations',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('.bio-hero').dataset.ambient === 'running');
    await page.locator('.summary-tile').last().scrollIntoViewIfNeeded();
    await page.waitForFunction(() => [...document.querySelectorAll('.summary-tile')].every(el => el.dataset.motionSeen === 'true'));
    await page.waitForTimeout(1300);
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.waitForFunction(() => document.querySelector('.bio-hero').dataset.ambient === 'running');
    await page.screenshot({path:'/tmp/healthee-motion-today.png', animations:'disabled'});
    await page.evaluate(() => document.querySelector('#daytime').scrollIntoView());
    await page.waitForFunction(() => document.querySelector('.bio-hero').dataset.ambient === 'paused');
    const paused = await halo.evaluate(el => el.toDataURL());
    await page.waitForTimeout(150);
    assert.equal(await halo.evaluate(el => el.toDataURL()), paused);
    await page.locator('#bottom-nav a[href="#sleep"]').click();
    await page.locator('.sleep-check').first().waitFor();
    assert.equal(await page.locator('.sleep-check').count(),4);
    await page.locator('#bottom-nav a[href="#today"]').click();
    await page.locator('.bio-hero').waitFor();
    await page.evaluate(() => window.scrollTo(0,0));
    assert.equal(await page.locator('.bio-hero').getAttribute('data-motion-seen'),'true');
    assert.equal(await page.locator('.age-value').textContent(),'34.3years');
    assert.equal(await page.locator('.bio-hero').evaluate(el => el.getAnimations().length),0,'Returning to a screen must not replay the entry');
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.waitForFunction(() => document.documentElement.dataset.motion === 'off');
    const still = await halo.evaluate(el => el.toDataURL());
    await page.waitForTimeout(150);
    assert.equal(await halo.evaluate(el => el.toDataURL()),still);
    assert.equal(await page.locator('.bio-hero [data-action="motion"]').isDisabled(),true);
    await page.evaluate(() => H.navigate('body'));
    await page.waitForURL('**/#body');
    assert.equal(await page.locator('.age-value').textContent(),'34.3years');
    assert.equal(await page.locator('.bio-halo').evaluate(el => getComputedStyle(el).opacity),'1');
    await page.emulateMedia({reducedMotion:'no-preference'});
    await page.waitForFunction(() => document.documentElement.dataset.motion === 'on');
    await page.locator('.preview-bar button').click();
    await page.locator('#sheet [data-action="motion"]').click();
    assert.equal(await page.locator('#sheet .motion-label').textContent(),'Resume animations');
    console.log('Motion verified: animation, pause/resume, offscreen pause, stable values, no replay, reduced motion and four sleep checks.');
  } finally { await browser.close(); }
}
main().catch(error => { console.error(error); process.exitCode=1; });
